apiVersion: v1
kind: Service
metadata:
  name: simple-webapp-svc
  namespace: webapp
spec:
  type: NodePort
  selector:
    app: simple-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008
